### ISSUE TITLE
Create or find an appropriate people counter algorithm

### ISSUE THREAD

**Issue by Jaffenheimer** [Jaffenheimer/P8-Mobility#1]

**Comment by JJTM20** [comment]
- [x] Setup project 
- [x] Find best HOG Descriptor (Looks like we only have the `DefaultPeopleDetector` and `DaimlerPeopleDetector`
- [ ] Finish Utility testing
- [x] Test real time at bus stop
- [ ] Create a service hosted at the busstop controlling the one camera, and post the amount of people and Id of busstop to backend/controller
